api request returns stackflow questions' title based on tags
BarlesCharkley75/ExampleBot pull request #9
Opened 2021-04-21 05:34 UTC by krixstin

tags are 

- "api" by default
- user's "method", 
- user's "library"

2021-04-23 22:49 UTC, carpenterd777 requested changes

2021-04-23 22:49 UTC, carpenterd777 commented on src/api_stackflow.js
> +var library=""
```suggestion
let method="";
let library="";
```

2021-04-23 22:49 UTC, carpenterd777 commented on src/api_stackflow.js
> +var library=""
we should use `let` or `const` for variables when we can. `var` is a bit outdated as all variables created with it are global

2021-04-23 22:49 UTC, carpenterd777 commented on src/api_stackflow.js
> +//install npm i node-fetch --save
could you run `npm i node-fetch` and push the updated `package.json`? we'll all be able to install the new dependency automatically with `npm i` once that file is updated

2021-04-23 22:49 UTC, carpenterd777 commented on src/api_stackflow.js
> +        // console.log(data); //see json file
```suggestion
```

2021-04-23 22:49 UTC, carpenterd777 commented on src/api_stackflow.js
> +            var title = data.items[i].title;
```suggestion
            let title = data.items[i].title;
```

2021-04-23 22:49 UTC, carpenterd777 commented on src/api_stackflow.js
> +get_stackflow("post","java");
```suggestion
export default get_stackflow
```

2021-04-23 22:49 UTC, carpenterd777 commented on src/api_stackflow.js
> +get_stackflow("post","java");
this will allow us to import the function in say, `index.ts`.

2021-04-24 01:38 UTC, carpenterd777 commented on src/api_stackflow.js
> +        var data = await response.json(); //store "response" in form of Json
```suggestion
        let data = await response.json(); //store "response" in form of Json
```

2021-04-24 01:41 UTC, carpenterd777 commented
Closes #5

2021-04-24 02:02 UTC, carpenterd777 commented on src/api_stackflow.js
> +let library="";
```suggestion
```

2021-04-24 02:03 UTC, carpenterd777 commented on src/api_stackflow.js
> +let library="";
no need to declare these since they are declared as function parameters below

2021-04-24 02:17 UTC, carpenterd777 requested changes
I tried calling `get_stackflow` with the arguments "print" and "java" and got the following result:

```
METHOD:  PRINT 
 LIBRARY: JAVA 

Title 1 :  API for printers?
Title 2 :  How do you print off a Java Book?
Title 3 :  how to force Java print graphics in 300dpi
Title 4 :  Print Microsoft Office and PDF files in Java
/home/electricolor/Documents/s2021/modsim/ExampleBot/build/src/api_stackflow.js:56
                            title = data.items[i].title;
                                                  ^

TypeError: Cannot read property 'title' of undefined
    at /home/electricolor/Documents/s2021/modsim/ExampleBot/build/src/api_stackflow.js:56:51
    at step (/home/electricolor/Documents/s2021/modsim/ExampleBot/build/src/api_stackflow.js:33:23)
    at Object.next (/home/electricolor/Documents/s2021/modsim/ExampleBot/build/src/api_stackflow.js:14:53)
    at fulfilled (/home/electricolor/Documents/s2021/modsim/ExampleBot/build/src/api_stackflow.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

2021-04-25 03:45 UTC, krixstin commented
@carpenterd777 I figured that there were only 4 posts that have "API", "print" and "java" tags from my API request. 

I reformatted the function from "returning something" from StackOverflow to 
"returning one post link of a question that's answered & returning error message if none of reqs met"

2021-04-25 15:01 UTC, carpenterd777 requested changes
lets try and have the bot return the actual results from one or more stack exchange posts. if we return a link, the user would be able to get the same functionality from google instead, and the idea of our bot was to be accessible from within discord

2021-04-25 16:47 UTC, carpenterd777 approved these changes

2021-04-25 16:48 UTC, merged